name: Houtootje
favicon: null
layout_spectrum: 0.52122
typography_spectrum: 0.5125
title: "Coole auto's van hout, voor jong en oud"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc7229'
    - '#ebecee'
    - '#ccb4b2'
    - '#2f1508'
    - '#8a7675'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
